### ISSUE TITLE
[Bug]: Light Blue Sheep Head doesn't drop

### ISSUE THREAD

**Issue by Toastr125** [Mrbysco/Heads#3]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.2

### Mod version

1.0.4

### Java version

Java 17.0.3 64bit

### Issue Description

For some reason, the light blue sheep head in particular doesn't drop. After killing around 500 light blue sheep with looting 3 on a server, I finally figured that there might be some glitch going on so I tested with a looting 255 sword in single player. I spawned several random color sheep as a control group and all of them dropped their heads, but I tried it on a dozen or so light blue sheep and not a single one dropped their head. I was able to get every single other color of sheep head, so this is specific to light blue.

**Comment by Mrbysco** [comment]
A new version will be up shortly fixing the problem
